[package]
name = "alpaca"
version = "0.3.0"
edition = "2018"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0-or-later"
description = """
A create for interacting with the Alpaca API.
"""

[dependencies]
chrono = {version = "0.4", default-features = false}
futures = {version = "0.3", default-features = false}
http-endpoint = {version = "0.1", git = "ssh://rpigit/~/git/http-endpoint.git"}
num-decimal = {version = "0.1", git = "ssh://rpigit/~/git/num-decimal.git", features = ["serde"]}
hyper = {version = "0.13", features = ["stream"]}
hyper-tls = {version = "0.4", default-features = false}
log = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
trace = {version = "0.1", git = "ssh://rpigit/~/git/trace.git"}
tungstenite = {package = "async-tungstenite", version = "0.3", features = ["tokio-runtime", "tokio-tls"]}
url = "2.0"
uuid = {version = "0.8", default-features = false, features = ["serde", "v4"]}
websocket-util = {version = "0.2", git = "ssh://rpigit/~/git/websocket-util.git"}

[dev-dependencies]
env_logger = {version = "0.7", default-features = false}
test-env-log = "0.2"
tokio = {version = "0.2", default-features = false, features = ["rt-core", "macros"]}
websocket-util = {version = "0.2", git = "ssh://rpigit/~/git/websocket-util.git", features = ["test"]}
