[package]
name = "alpaca"
version = "0.7.0"
edition = "2018"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0-or-later"
description = """
A create for interacting with the Alpaca API.
"""

[dependencies]
chrono = {version = "0.4", default-features = false}
futures = {version = "0.3", default-features = false}
http-endpoint = {version = "0.1.1", git = "ssh://rpigit/~/git/http-endpoint.git"}
hyper = {version = "0.13", features = ["stream"]}
hyper-tls = {version = "0.4", default-features = false}
num-decimal = {version = "0.1", git = "ssh://rpigit/~/git/num-decimal.git", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0", default-features = false}
serde_urlencoded = {version = "0.6", default-features = false}
serde_variant = {version = "0.1", default-features = false}
time-util = {version = "0.1", git = "ssh://rpigit/~/git/time-util.git"}
tracing = {version = "0.1", default-features = false, features = ["std"]}
tracing-futures = {version = "0.2", default-features = false, features = ["std-future"]}
tungstenite = {package = "async-tungstenite", version = "0.4", features = ["tokio-runtime", "tokio-tls"]}
url = "2.0"
uuid = {version = "0.8", default-features = false, features = ["serde", "v4"]}
websocket-util = {version = "0.3", git = "ssh://rpigit/~/git/websocket-util.git"}

[dev-dependencies]
test-env-log = {version = "0.2.2", default-features = false, features = ["trace"]}
tokio = {version = "0.2", default-features = false, features = ["rt-core", "macros"]}
tracing-subscriber = {version = "0.1.6", default-features = false, features = ["ansi", "chrono", "env-filter", "fmt"]}
websocket-util = {version = "0.3", git = "ssh://rpigit/~/git/websocket-util.git", features = ["test"]}
